---
- hosts: '{{ target }}'
  remote_user: root

  tasks:
  - name: Install Zabbix agent
    apt:
      name: zabbix-agent
      state: present
      update_cache: yes

  - name: Config server
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server='
      line: 'Server={{ server }}'

  - name: Config host name
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Hostname='
      line: 'Hostname={{ target }}'

  - name: Restart Zabbix agent
    service:
      name: zabbix-agent
      state: restarted
