---
- hosts: '{{ target | default("mariadb_simple") }}'
  remote_user: root

  tasks:
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present

  - name: Install MariaDB
    apt:
      name: mariadb-server
      state: present

  - name: Ensure that MariaDB is started
    service:
      name: mysql
      state: started

  - name: Create databases with name "default_db"
    mysql_db:
      name: default_db
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Create database user with password "default_password"
    mysql_user:
      name: default_user
      password: '*E4A037873BF6C039358C12D2B772D39954E0DC79'
      encrypted: yes
      state: present
      priv: 'default_db.*:ALL'
      login_unix_socket: /var/run/mysqld/mysqld.sock
      host: '%'

  - name: Copy my.cnf
    copy:
      src: my.cnf
      dest: /etc/mysql/my.cnf
      mode: 0644

  - name: Restart MariaDB
    service:
      name: mysql
      state: restarted
